### ISSUE TITLE
passencode.py errors due to INITAL_PASS typo

### ISSUE THREAD

**Issue by makuk66** [pdubois/docker-alfresco#2]
The documentation describes the `INITIAL_PASS` environment variable in e.g. https://github.com/pdubois/docker-alfresco/blame/master/README.md#L16.
But, in most places the environment variable is `INITAL_PASS`, missing an `I`.
As a result, things go wrong. From a `docker logs`:

```
Cleaning temporary Alfresco files from Tomcat...
Traceback (most recent call last):
  File "/passencode.py", line 4, in <module>
    encrypted = hashlib.new('md4', passwd.encode('utf-16le')).hexdigest()
AttributeError: 'NoneType' object has no attribute 'encode'
waiting for server to start.... done
```

**Comment by pdubois** [comment]
Thanks. It is resolved now.
