### ISSUE TITLE
hardcoded export PGPASSWORD=mysecretpassword in entry.sh

### ISSUE THREAD

**Issue by joeribelis** [pdubois/docker-alfresco#6]
hardcoded export PGPASSWORD=mysecretpassword in entry.sh

so using the -e ALF_2='db.password.123ABC' will not work

**Comment by andraskelemen** [comment]
This is still an issue in v5.2

**Comment by deadman2000** [comment]
Why this issue is closed? It's still problem. I can't run it with different password in postgres
